<%@ Page Title="" Language="C#" MasterPageFile="~/master.Master" AutoEventWireup="true" CodeBehind="kural.aspx.cs" Inherits="ejder3200.kural" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
<style>
    h3{
        color:white;
        font-weight: bold;
    }
    p{
        color:white
    }
</style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
      <div style="padding:20px;margin:20px; text-align:center;"> 
        
          <img  src="img/A1.jpeg" alt="" style="width:100%;height:500px; margin:10px" />
          <h3> PİST VE LİFT KURALLARI </h3>
<p>Lift Kullanımında Dikkat Edilip Uygulanması Gereken Talimatlar<br />
1-) Liftlere iniş binişler gösterilen bölgelerden yapılmalıdır.<br />
2-) Lift operatörünün yerinde olmadığı durumlarda lifti kullanmayınız.<br />
3-) Snowboard kullanıcılarının, lifte bindikleri andan itibaren ininceye kadar ayakları serbest, snowboardları açık kalmalıdır.<br />
4-) Boyları 1,25m’nin altında olan çocuklar, lifti tek başına kullanamazlar.<br />
5-) Lifte binerken sırt çantanızı sırtınızdan çıkartın.<br />
6-) Güvenlik barını lift hareket ettikten sonra hemen indiriniz ve iniş bölümüne varmadan hemen önce kaldırınız.<br />
7-) Liftin aniden durması halinde lütfen sakinliğinizi koruyunuz ve operatörlerden gelecek olan talimatları bekleyiniz.<br />
8-) Bekleme alanı olarak turnike bölgesinin dışını kullanınız.<br />
9-) Liftleri kayak amaçlı kullananların, kayakları elinde tutması tehlikeli ve yasaktır.<br />
10-) Acil durumlarda +90 533 619 18 25 ya da 112 arayınız.<br />
11-) Yürüyen halı liftlerine biniş ve inişler, sadece başlangıç ve bitiş noktalarından yapılmalıdır. Ortadan, kenardan vs. yapılan biniş ve inişler tehlikeli ve yasaktır.<br />
12-) Misafirlerimiz liftleri kullanırken biniş ve iniş noktalarında bulunan operatörlerin yönlendirmelerine uymak zorundadır.<br />
13-) Lift kullanımlarında yaşlı, engelli ve yetkili personelin geçiş üstünlükleri vardır.<br />
14-) Lift kumanda odasına girmek tehlikeli ve yasaktır.<br />
15-) Liftleri, belirtilen açılış ve kapanış saatleri dışında lütfen kullanmayınız.<br />
16-) Arıza, olumsuz hava şartları vs. herhangi bir sebepten dolayı liftin kapatılması talimatını veren lift yöneticisinin, açılması uygundur talimatını verene kadar lütfen lifti kullanmayı talep etmeyiniz.<br />
17-) Lift kullanırken; sandalyede yan oturmak, zıplamak, ayağa kalkmak, güvenlik barını gereken yer dışında kaldırmak vb. tehlike arz edebilecek hal ve hareketlerde bulunmak kesinlikle tehlikeli ve yasaktır.<br />
18-) Tesisleri kullanırken mekanik aksamlara zarar vermemenizi ve çevreye çöp atmamanızı rica ederiz.  <br />
</p>
<h3> Instructions to Be Considered and Followed While Using the Lift</h3>
<p>1-) Getting on and off the lifts must be done from the areas shown.<br />
2-) Do not use the lift when the lift operator is not in place.<br />
3-) Snowboard users should keep their feet free and their snowboards open from the moment they get on the lift until they get off.<br />
4-) Children under 1.25m in height cannot use the lift alone.<br />
5-) Take your backpack off your back while getting on the lift.<br />
6-) Lower the safety bar immediately after the lift moves and lift it just before reaching the landing section.<br />
7-) In case the lift stops suddenly, please keep your calm and wait for the instructions from the operators.<br />
8-) Use the outside of the turnstile area as a waiting area.<br />
9-) It is dangerous and forbidden for those who use the lifts for skiing to hold the skis in their hands.<br />
10-) In case of emergency, call +90 533 619 18 25 or 112.<br />
11-) Embarking and disembarking on the moving carpet lifts should be done only from the starting and ending points. Middle, side etc. Embarkation and disembarkation is dangerous and prohibited.<br />
12-) Our guests must follow the directions of the operators at the boarding and landing points while using the lifts.<br />
13-) Elderly, disabled and authorized personnel have transition advantages in lift usage.<br />
14-) It is dangerous and forbidden to enter the lift control room.<br />
15-) Please do not use the lifts outside the specified opening and closing hours.<br />
16-) Failure, adverse weather conditions, etc. Please do not request to use the lift until the lift manager who gives the instruction to close the lift for any reason gives the instruction that it is ok to open.<br />
17-) When using a lift; sitting sideways in a chair, jumping, standing up, lifting the safety bar out of place, etc. It is absolutely dangerous and prohibited to engage in dangerous situations and actions.<br />
18-) While using the facilities, we kindly ask you not to damage the mechanical parts and not to throw garbage in the environment. <br /> 
</p><h3> Palandöken Kayak Merkezi Uyulması Gereken Kurallar</h3> <br />
<p>1 -) Palandöken Kayak Merkezi girişi olan ve “0” noktası olarak adlandırılan (Palandöken Yazısından başlayıp Özel Güvenlik Kulübesi, Jandarma Noktası, Polat Otel Telesiyej iniş istasyonu, Dedeman Ski Lodge Oteli bahçesi ile çevrili alan) yerden itibaren kayak pistlerine dahil kabul edildiğinden araç trafiğine kapatılacaktır. Güvenlik noktası bariyerinden itibaren hiçbir aracın giriş ve çıkışına müsaade edilmeyecektir.<br />
2- ) İl protokolüne ait araçlar ile Jandarma, Jandarma Arama Kurtarma (JAK) araçları ve ambulans belirlenecek park alanlarında park edecek, yeterli gelmemesi halinde alternatif park alanlarına yönlendirilecektir.
<br />3-) Palandöken Destinasyonu’ nda Ejder Kafe, Güney Kafe, Küre Kafe, Palandöken Kafe, Kapsül Kafe mahalleri arasındaki alan başta olmak üzere tüm kayak pistlerinde yerli ve yabancı misafirler yaya olarak seyahat etmektedir. Bu durum destinasyonda kayak ve snowboard yapan amatör ve profesyonel misafirlerle yaya vaziyette seyahat edenlerin çarpışmalarına sebebiyet vermekte olup istenmeyen kazalar meydana gelmektedir. Bu sebeple kayak pistlerinde bölgede yerli ve yabancı misafirlerin yaya olarak gezinti yapmaları yasaklanmıştır. Yaya olarak seyahat etmek isteyen yerli ve yabancı misafirlerin kayak pisti içerisine girmeden gondol ve telesiyej hatları aracılığıyla lift üst istasyonlarının 50 metreden fazla uzağına gitmeksizin seyahat etmelerinde bir sakınca bulunmamaktadır.
<br />4-) Destinasyon içerisinde Ejder 3200 Arama Kurtarma, Jandarma Arama Kurtarma, AFAD, UMKE kuruluşlarının dışındaki kurum-kuruluşlara ait veya hususi kullanıma mahsus motorlu-motorsuz kar üstü araç, taşıma kızağı, sedye, bot, kano gibi araçların kullanılması misafirlerin hayatlarını yüksek derecede riske atmaktadır. Kaza, kaybolma, mahsur kalma gibi olayların önlenebilmesi için bu tür araçların bahsi geçen kurum-kuruluşlar dışında aidiyeti olanlarının destinasyona girişi yasaktır.
<br />5-) Kar motorları kurumların kullanımı veya kiralanması halinde kiralandığı andan itibaren park alanı olarak belirtilen bölgeden (Destinasyon Girişi, Bilet Ofislerinin Önü) hareket ederek Ejder 3200’ ün belirlediği rotalarda seyahat edebilmesi, kayak pisti bölgesine rutin hallerde (Ejder 3200’ ün talep destek etmediği haller) sadece Jandarma Arama Kurtarma timine, Ejder 3200 teknik birimlerine ve Ejder 3200 Arama Kurtarma timine ait kar motosikletlerin devriye ve arama kurtarma görevi için girmeleri, destinasyonda arama kurtarma faaliyetlerini öncelikli olarak Ejder 3200 ekiplerinin yürütmesi ve yeterli kalmaması halinde JAK birimlerinden destek alması uygun görülmüştür.
<br />6-) Kar motosikletlerinin yolculara veya yaralılara kullandırılmasına yerli ve yabancı misafirlerin can güvenliğini tehlikeye sokmamaları adına müsaade edilmesi yasaktır.
<br />7-) Kızak pisti olarak; Kapsül Kafe’ nin batı kenarının kullanılmasının uygun olduğu karalaştırılmış olup kayak pistlerinde kızakla kaymak yasaktır.
<br />8-) Kayak öğretici yönetmeliğinin madde: 16 ve 17 göre kayak öğretici lisansı olup vizesini yaptırmayanlar ile antrenör ve hiçbir belgeye sahip olmayan kişilerin ders veremeyeceği antrenör konumda olan kişilerinde sadece sporcu çalıştırabileceği ve kayak öğreticilerinin yanında yardımcı olarak çalıştırabileceği, madde 15'e göre ise kayak öğreticilerin Genel Müdürlükçe belirlenen ders ücretinin altında ve ya üstünde ücret almayacakları belirtilmiş olup, Palandöken kayak pistlerine gelen yerli ve yabancı misafir sayısının fazla olması ve buna karşılık kayak öğretmenlerinin sayılarının az olması sebebiyle kayak öğretmenleri derneğinin sorumluluğu ve gözetimi altında antrenör belgesi olanlar da ders verebilecek, dernekten alınacak belge aracılığı ile ancak ders verilmesi mümkün olacak, hiçbir belgesi olmayanlar kati suretle ders veremeyecektir.
<br />9-) Çevre kirliliğinin önlenebilmesi için piknik faaliyetlerinin Palandöken Destinasyonu’ nun herhangi bir konumunda gerçekleştirilmesi yasaktır.
<br />10-) Kayak ve kızak pistlerine, özellikle pistin kapanmasından sonra 4x4 arazi tipi araçlar ve ATV-motosikletler ile girerek kayak pistine zarar verilmekte olup, her tür motorlu-motorsuz araçla kayak pistine girilmesi yasaktır.
<br />11-) Kayak ve kızak pistlerinde kask ve kayak kıyafeti kullanılmaması sebebiyle, meydana gelen kazalarda hasar miktarının yoğun olduğu tespit edilmiştir. Bu sebeple kayak pistlerinde kask ve kayak kıyafeti olmadan faaliyet yapmak, herhangi bir kayak materyali varken kask veya kayak kıyafetinin olmadığı hallerde lift-gondol-tbar gibi tesislere binmek veya pistte faaliyet yürütmek yasaktır.
<br />12-) Görünen engeller, çarpışma ve yaralanma riski barındıran her türlü engel ve yüksekten düşme vb. risklere karşı misafirlerin kendi önlemlerini almaları riskli bölgelere yaklaşmamaları gerekmektedir.
<br />13-) Palandöken Destinasyonu’ na yaz ve kış sezonunda dağcılık ve kampçılık faaliyetleri için gelen yerli ve yabancı misafirlerin kaybolma, yaralanma, mahsur kalma gibi vakalar yaşamaları halinde kendilerine daha hızlı yardımda bulunabilmesi için; faaliyetlerine başlamadan önce gerekli belge araç ve malzemeleri ile birlikte Palandöken Jandarma Karakol Komutanlığı’ na Ejder Kayak Merkezleri A.Ş.’ den olur yazısı almak suretiyle müracaat etmelerinin uygun olacağı, aksi takdirde arama kurtarma faaliyetlerinde gecikmeye sebebiyet verileceği ve misafirlerin hayatlarının tehlikeye maruz kalmalarına neden olunacağı için Palandöken J.Krk.K.lığına müracaat ederek kayıtlarını yaptırmaları, mevcut sezon durumuna göre malzemelerinin kontrolünü yaptırarak eksik malzemelerin tamamlanması gerekmektedir.
<br />14-) Destinasyon içerisinde bulunan tırmanış, kayak, snowboard, kızak, kamp, vb. rekreasyon alanlarının tamamında yapılacak bütün faaliyetlerin yüksek enerji, güvenlik, disiplin ve koordinasyon gerektirdiği tespit edilmiş olup; faaliyetlerden biri veya birkaçını yürüten bütün misafirlerin yaralanma, sakatlanma, psikolojik zarar görme gibi ihtimallerin tümünün bilincinde olması gerektiği ve kendi can güvenliği için emniyetli davranışlarda bulunması ve tüm sorumluluğun kendinde olduğunun bilincinde olması gerekmektedir.
<br />15-) Palandöken ve Konaklı Kayak Merkezleri’ nin bulunduğu Palandöken Destinasyonu’ nda her ne sebeple olursa olsun bulunan tüm misafirler Destinasyon Kuralları’ na ve uyarı levha-tabelalarına, yasaklarına uymakla mükelleftir. Ejder 3200 Arama Kurtarma Timinin ve Ejder 3200 Personelinin risklere, kurallara, yasaklara ilişkin uyarmada ve negatif davranışın sürekliliği halinde destinasyondan kolluk kuvvetleri tarafından uzaklaştırılması kararını verme ve lift kullanım kartlarını iptal etme hususunda yetkilidir.
<br />16-) Destinasyonda her ne sebeple olursa olsun bulunan tüm oteller ve işletmeler kendi yapısal alanlarının kayak pistlerine uygunluğu ve güvenlik zafiyetinden sorumludur.
<br />17-) Olası görünen risk alanlarında önlem gözetmeksizin risk almama ve riskli alana yaklaşmama sorumluluğu misafirin iradesindedir.
<br />18-) Palandöken yazısı batı tarafında 5 araçlık protokol araç yeri belirlenmiş olup, sınırlandırılan alanlar dışında Palandöken Yazısı etrafında park yapılması yasatır. Jandarma, Emniyet, Sağlık, İtfaiye, Zabıta, Umke, Afad gibi kurumların acil durumlara müdahale araçlarının park konumlarının Kayak alanlarını tehlikeye atmadan, Palandöken yazısı etrafında olmaması gerekmektedir. Jak tim aracı ve Ambulans Araçları için Palandöken yazısı yanında alanlar tahsis edilecektir.
<br />19-) Pistlerde ve pist sınırları dışında sorumluluk tamamen sizindir. Pist güvenlik & arama kurtarma personeli sizleri kazalara karşı uyarmak, olası kazalarda pist üzerinde sizlere müdahale etmeye yetkili ekiptir. Pist güvenlik ekiplerinin sizlere ulan uyarılarına özen göstermeli olası kazalarda doğru ve net bilgi vermelisiniz.
<br />20-) Pistler üzerinden bulunan güvenlik gereçleri sizi uyarmak ve beklenmeyen kazaları karşı alınan tedbirlerdir.
<br />21-) Pist içerisinde oluşan kazalarda sertifika yetkisi ile İlk Yardım uygulamasını gerçekleştirmeye tek yetkili birim Pist Güvenlik & Arama Kurtarma Ekipleridir.
<br />22-) Kapalı pistlerden kaymak kesinlikle yasaktır sorumluluk size aittir.
<br />23-) Arama Kurtarma ve pist güvenlik personelinin talimatlarına uymak zorunludur  <br />
</p><h3> Palandöken Ski Center Rules to be Followed</h3> <br />
<p>1 -) Palandöken Ski Resort and is the entrance to the “0” point (called the article Palandoken start from the booth and private security, Gendarmerie Point, the landing ski lift station Polat hotel, dedeman Ski Lodge Hotel, surrounded by a garden with area) will be closed to vehicle traffic since it is accepted, including from the ski slopes. No vehicle will be allowed to enter and exit from the security point barrier.
<br />
        2- ) Vehicles belonging to the provincial protocol, Gendarmerie, Gendarmerie Search and Rescue (Dec) vehicles and ambulances will park in the parking areas to be determined, and if they are not enough, they will be directed to alternative parking areas.
<br />3-) Domestic and foreign guests travel on foot on all ski slopes, especially in the area between Deckhouse Cafe, Southern Cafe, Kure Cafe, Palandoken Cafe, Capsule Cafe, Dragon Cafe, Cafe in the Palandoken Destination. This situation leads to collisions between amateur and professional guests skiing and snowboarding at the destination and those traveling on foot, and unwanted accidents occur. For this reason, it is forbidden for local and foreign guests to walk on the ski slopes in the region. There is no objection for domestic and foreign guests who want to travel on foot to travel more than 50 meters away from the lift upper stations via gondola and chairlift lines without entering the ski slope.
<br />4-) The Dragon in the destination 3200, search and rescue, search and rescue, Jandarma, AFAD, and National Medical Rescue institutions that are outside the organization-owned or private institutions use for motorized and non-motorized snow vehicle, carriage and sleigh, stretcher, boating, canoeing, risking their lives is the use of tools such as a high degree of your guests. In order to prevent incidents such as accidents, disappearances, being stranded, the entry of such vehicles to the destination of those who belong to other than the mentioned institutions-organizations is prohibited.
<br />5-) or a third party hired to the use of the snow engines institutions from the moment the parking area for the specified area (Destination Entry, in front of the ticket office) by acting 3200 Dragon’ s able to travel on designated routes, to the ski area in routine cases (Ejder 3200’ s claim does not support in cases where only) Gendarmerie search and Rescue Team, Dragon and Dragon snowmobile 3200 3200 technical units for the mission of the patrol and search and rescue search and rescue team to enter, it was deemed appropriate that the Ejder 3200 teams should carry out the search and rescue activities at the destination as a priority and receive support from Dec units if there is not enough.
<br />6-) It is forbidden to allow snowmobiles to be used by passengers or injured people in order not to endanger the life safety of domestic and foreign guests.
<br />7-) As a toboggan run; It is blackened that the western edge of the Capsule Cafe is suitable for use, and sledding is prohibited on the ski slopes.
<br />8-) according to Article 16 and 17 of the regulation tutorial skiing, ski license and a visa with those who have the tutorial the coach and the course of people who do not have any document that can give the athlete and coach can run only in persons who are in the position of the utility can run as next ski tutorial, Article 15, according to the ski instructors of the course fee, as determined by the General Directorate of charge are under or on top, they wouldn't, Palandoken Ski from the ski slopes and contrast the number of local and foreign guests in the number of teachers is low, because under the supervision and responsibility of those teachers association ski coach certificate course able to give, through the document to be obtained from the association, but you will be able to teach, no document is non-rigid manner, you will not be able to give you a course in.
<br />9-) It is forbidden to carry out picnic activities at any location of Palandoken Destination in order to prevent environmental pollution.
<br />10-) Damage is caused to the ski slope by entering the ski and toboggan slopes, especially with 4x4 off-road vehicles and ATV-motorcycles after the closure of the runway, and it is forbidden to enter the ski slope with all types of motorized and non-motorized vehicles.
<br />11-) Due to the fact that helmets and ski suits are not used on ski and toboggan runs, it has been determined that the amount of damage is intense in the accidents that occur. For this reason, it is forbidden to operate on ski slopes without a helmet and ski clothing, to ride in facilities such as lift-gondola-tbar or to carry out activities on the piste in cases where there is no helmet or ski clothing while there is any ski equipment.
<br />12-) Visible obstacles, all kinds of obstacles that pose a risk of collision and injury, and falling from a height, etc. guests should take their own precautions against risks and should not approach risky areas.
<br />13-) Palandoken season mountaineering and camping activities summer and winter destination of domestic and foreign guests to and from loss, injury, trapped in order to help them more quickly if they have cases like a; before starting its activities, the necessary documents together with the tools and materials to the Palandoken Gendarmerie Outpost Command Dragon Ski Resorts A.Sh. it will be appropriate for them to apply by receiving a letter of Decency from Palandoken J., otherwise it will cause a delay in search and rescue activities and cause the guests' lives to be exposed to danger.Krk.K.it is necessary for them to make their registrations by applying to the university, to complete the missing materials by having their materials checked according to the current season situation.
<br />14-) Climbing, skiing, snowboarding, sledding, camping, etc. within the destination. the recreation to be made of all the activities in all fields of high-energy, security, discipline, and coordination has been identified that requires; of all the guests that executes one or more activities of injury, psychological harm should be aware of all possibilities and for your own safety, such as to engage in safe behavior, and should be aware that in itself of all responsibility.
<br />15-) All guests who are located in the Palandoken Destination, where the Palandoken and Konakli Ski Resorts are located, for whatever reason, are obliged to comply with the Destination Rules and warning signs, prohibitions. 3200 3200 Dragon Dragon team and search and rescue Personnel risks, rules, prohibitions and negative in relation to the WARN be removed by law enforcement from destinations in the continuity of behavior and the lift is authorized to make the decision to revoke the use of the cards.
<br />16-) All hotels and enterprises located in the destination for whatever reason are responsible for the suitability of their structural areas for the ski slopes and for the safety vulnerability.
<br />17-) The responsibility of not taking risks and not approaching the risky area without taking precautions in the possible risk areas is at the will of the guest.
<br />18-) The protocol vehicle location for 5 cars has been determined on the west side of the Palandoken inscription and it is legal to park around the Palandoken Inscription except for the restricted areas. Gendarmerie, Security, Health, Fire Brigade, Police, Umke, Afad institutions such as emergency response vehicles parking locations should not be around the Palandoken inscription without endangering the ski areas. Areas will be allocated next to the Palandoken inscription for the Jack team vehicle and Ambulance Vehicles.
<br />19-) The responsibility is completely yours on the tracks and outside the track boundaries. Runway security & search and rescue personnel are the team authorized to warn you against accidents and intervene Decently on the runway in case of possible accidents. You should pay attention to the warnings of the runway safety teams and give accurate and clear information in case of possible accidents.
<br />20-) Safety equipment located on the tracks are measures taken to warn you and prevent unexpected accidents.
<br />21-) The only authorized unit to perform First Aid application with Decertification authority in accidents occurring on the runway is Runway Security & Search and Rescue Teams.
<br />22-) Skiing on closed tracks is strictly prohibited, the responsibility belongs to you. 23-) It is obligatory to comply with the instructions of the Search and Rescue and runway security personnel
    </p>
</div>
</asp:Content>
